//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContracImage
    {
        public long ContracImageId { get; set; }
        public Nullable<long> ContractId { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public string Files { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
