//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guide
    {
        public Guide()
        {
            this.GuidesPrices = new HashSet<GuidesPrice>();
            this.GuidesPropertyDetails = new HashSet<GuidesPropertyDetail>();
        }
    
        public int GuidesId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> VocativeId { get; set; }
        public string NumberIdentity { get; set; }
        public string Birthday { get; set; }
        public string PlaceOfIssue { get; set; }
        public string DayOfIssue { get; set; }
        public string NumberVat { get; set; }
        public bool IsMarriage { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Image { get; set; }
        public string Passport { get; set; }
        public System.DateTime FromPassport { get; set; }
        public Nullable<System.DateTime> ToPassport { get; set; }
        public Nullable<int> GuidesGroupId { get; set; }
        public Nullable<int> GuidesContractId { get; set; }
        public Nullable<int> FolkId { get; set; }
        public Nullable<int> ReligionId { get; set; }
        public int Nationatily { get; set; }
        public string Market { get; set; }
        public string Area { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Facebook { get; set; }
        public Nullable<int> NationalId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> WardId { get; set; }
        public string Address { get; set; }
        public string AddressShow { get; set; }
        public Nullable<int> EducationId { get; set; }
        public Nullable<int> CareerId { get; set; }
        public Nullable<int> Language { get; set; }
        public Nullable<int> GridesCardTypeId { get; set; }
        public Nullable<System.DateTime> FromGridesCardDay { get; set; }
        public Nullable<System.DateTime> ToGridesCardDay { get; set; }
        public string Experience { get; set; }
        public string Description { get; set; }
        public string Contents { get; set; }
        public Nullable<int> Status { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
    
        public virtual Folk Folk { get; set; }
        public virtual GridesCardType GridesCardType { get; set; }
        public virtual GuidesContract GuidesContract { get; set; }
        public virtual GuidesGroup GuidesGroup { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual Vocative Vocative { get; set; }
        public virtual ICollection<GuidesPrice> GuidesPrices { get; set; }
        public virtual ICollection<GuidesPropertyDetail> GuidesPropertyDetails { get; set; }
    }
}
