//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidesGroup
    {
        public GuidesGroup()
        {
            this.Guides = new HashSet<Guide>();
            this.GuidesPrices = new HashSet<GuidesPrice>();
        }
    
        public int GuidesGroupId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Market { get; set; }
        public string Area { get; set; }
        public string Language { get; set; }
        public Nullable<int> Status { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<Guide> Guides { get; set; }
        public virtual ICollection<GuidesPrice> GuidesPrices { get; set; }
    }
}
