//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidesPrice
    {
        public long GuidesPriceId { get; set; }
        public int GuidesId { get; set; }
        public Nullable<int> GuidesGroupId { get; set; }
        public Nullable<long> ContractId { get; set; }
        public Nullable<long> ProviderId { get; set; }
        public Nullable<int> PaymenId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> FromDay { get; set; }
        public Nullable<System.DateTime> ToDay { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PriceExtra { get; set; }
        public Nullable<bool> IsVat { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Guide Guide { get; set; }
        public virtual GuidesGroup GuidesGroup { get; set; }
        public virtual Payman Payman { get; set; }
    }
}
