//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidesPropertyDetail
    {
        public int GuidesPropertyId { get; set; }
        public int GuidesId { get; set; }
        public Nullable<int> Rank { get; set; }
        public string Note { get; set; }
    
        public virtual Guide Guide { get; set; }
        public virtual GuidesProperty GuidesProperty { get; set; }
    }
}
