//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Land
    {
        public long LandId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> QuantityDay { get; set; }
        public Nullable<int> QuantityNight { get; set; }
        public Nullable<int> NationalId { get; set; }
        public string Destination { get; set; }
        public string Description { get; set; }
        public string Contents { get; set; }
        public Nullable<int> QuantityGuest { get; set; }
        public Nullable<int> StarsId { get; set; }
        public Nullable<int> HotelNight { get; set; }
        public Nullable<int> Meal { get; set; }
        public Nullable<int> Snacks { get; set; }
        public string SortSchedule { get; set; }
        public string Files { get; set; }
        public Nullable<int> GroupGuestId { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual GroupGuest GroupGuest { get; set; }
        public virtual Star Star { get; set; }
    }
}
