//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentProfit
    {
        public long ParentProfitId { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Name { get; set; }
        public Nullable<double> Percents { get; set; }
        public Nullable<System.DateTime> FromDay { get; set; }
        public Nullable<System.DateTime> ToDay { get; set; }
    
        public virtual Partner Partner { get; set; }
    }
}
