//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParnertContact
    {
        public long ParnertContactId { get; set; }
        public Nullable<int> RegencyId { get; set; }
        public string ParnertId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sex { get; set; }
        public string NickName { get; set; }
        public string Phone { get; set; }
        public string HotLine { get; set; }
        public string Mail { get; set; }
        public string Note { get; set; }
    }
}
