//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerBranch
    {
        public long PartnerBarchId { get; set; }
        public Nullable<long> PartnerId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Hotline { get; set; }
        public string Mail { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Note { get; set; }
    
        public virtual Partner Partner { get; set; }
    }
}
