//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerStaffBank
    {
        public long PartnerStaffBankId { get; set; }
        public Nullable<long> PartnerStaffId { get; set; }
        public string NumberBank { get; set; }
        public Nullable<int> BankId { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual PartnerStaff PartnerStaff { get; set; }
    }
}
