//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerStaff
    {
        public PartnerStaff()
        {
            this.PartnerStaffBanks = new HashSet<PartnerStaffBank>();
        }
    
        public long PartnerStaffId { get; set; }
        public Nullable<long> PartnerId { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<int> VocativeId { get; set; }
        public string Name { get; set; }
        public string NumberIdentity { get; set; }
        public string Birthday { get; set; }
        public string PlaceOfIssue { get; set; }
        public string DayOfIssue { get; set; }
        public string NumberVat { get; set; }
        public bool IsMarriage { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Image { get; set; }
        public string Phone { get; set; }
        public string Phone1 { get; set; }
        public string Mail { get; set; }
        public string Mail1 { get; set; }
        public string ImageIdentity { get; set; }
        public string ImageBirth { get; set; }
        public string Note { get; set; }
        public Nullable<int> OriginNationalId { get; set; }
        public Nullable<int> OriginCityId { get; set; }
        public Nullable<int> OriginDistrictId { get; set; }
        public Nullable<int> OriginWardId { get; set; }
        public string OriginAddress { get; set; }
        public string OriginShow { get; set; }
        public Nullable<int> ContactNationalId { get; set; }
        public Nullable<int> ContactCityId { get; set; }
        public Nullable<int> ContactDistrictId { get; set; }
        public Nullable<int> ContactWardId { get; set; }
        public string ContactAddress { get; set; }
        public string ContactShow { get; set; }
        public Nullable<int> Status { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Vocative Vocative { get; set; }
        public virtual ICollection<PartnerStaffBank> PartnerStaffBanks { get; set; }
    }
}
