//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public Partner()
        {
            this.ParentProfits = new HashSet<ParentProfit>();
            this.PartnerBanks = new HashSet<PartnerBank>();
            this.PartnerBranches = new HashSet<PartnerBranch>();
            this.PartnerContacts = new HashSet<PartnerContact>();
            this.PartnerDeposits = new HashSet<PartnerDeposit>();
            this.PartnerImages = new HashSet<PartnerImage>();
            this.PartnerLeveDetails = new HashSet<PartnerLeveDetail>();
            this.PartnerPropertises = new HashSet<PartnerPropertise>();
            this.PartnerStaffs = new HashSet<PartnerStaff>();
        }
    
        public long PartnerId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NameOther { get; set; }
        public string NameSearch { get; set; }
        public string NumberSPKD { get; set; }
        public string NumberLHQT { get; set; }
        public string TaxCode { get; set; }
        public string EstablishYear { get; set; }
        public string Paymen { get; set; }
        public string MoneyDealId { get; set; }
        public string CardDealId { get; set; }
        public string Image { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public Nullable<int> CareerId { get; set; }
        public Nullable<int> NationalId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> WardId { get; set; }
        public string AddressShow { get; set; }
        public string ServiceId { get; set; }
        public string Description { get; set; }
        public string Contents { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
    
        public virtual ICollection<ParentProfit> ParentProfits { get; set; }
        public virtual ICollection<PartnerBank> PartnerBanks { get; set; }
        public virtual ICollection<PartnerBranch> PartnerBranches { get; set; }
        public virtual ICollection<PartnerContact> PartnerContacts { get; set; }
        public virtual ICollection<PartnerDeposit> PartnerDeposits { get; set; }
        public virtual ICollection<PartnerImage> PartnerImages { get; set; }
        public virtual ICollection<PartnerLeveDetail> PartnerLeveDetails { get; set; }
        public virtual ICollection<PartnerPropertise> PartnerPropertises { get; set; }
        public virtual ICollection<PartnerStaff> PartnerStaffs { get; set; }
    }
}
