//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerBank
    {
        public long PartnerId { get; set; }
        public int BankId { get; set; }
        public string Numbert { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
