//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerLeveDetail
    {
        public long PartnerId { get; set; }
        public int PartnerLeveId { get; set; }
        public Nullable<double> Percents { get; set; }
        public Nullable<System.DateTime> Day { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual PartnerLeve PartnerLeve { get; set; }
    }
}
