//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payman
    {
        public Payman()
        {
            this.GuidesPrices = new HashSet<GuidesPrice>();
            this.InsurancePrices = new HashSet<InsurancePrice>();
            this.ServiceOtherPrices = new HashSet<ServiceOtherPrice>();
        }
    
        public int PaymenId { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<GuidesPrice> GuidesPrices { get; set; }
        public virtual ICollection<InsurancePrice> InsurancePrices { get; set; }
        public virtual ICollection<ServiceOtherPrice> ServiceOtherPrices { get; set; }
    }
}
