//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.Contracts = new HashSet<Contract>();
            this.ProviderBanks = new HashSet<ProviderBank>();
            this.ProviderBranches = new HashSet<ProviderBranch>();
            this.ProviderImages = new HashSet<ProviderImage>();
            this.ProviderPropertises = new HashSet<ProviderPropertise>();
            this.ServiceOtherPrices = new HashSet<ServiceOtherPrice>();
        }
    
        public long ProviderId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string NameOther { get; set; }
        public string NameSearch { get; set; }
        public string NumberSPKD { get; set; }
        public string NumberLHQT { get; set; }
        public string TaxCode { get; set; }
        public string EstablishYear { get; set; }
        public string Paymen { get; set; }
        public string MoneyDealId { get; set; }
        public string CardDealId { get; set; }
        public string Image { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public Nullable<int> CareerId { get; set; }
        public Nullable<int> NationalId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string AddressShow { get; set; }
        public string ServiceId { get; set; }
        public string Description { get; set; }
        public string Contents { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
    
        public virtual Career Career { get; set; }
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<ProviderBank> ProviderBanks { get; set; }
        public virtual ICollection<ProviderBranch> ProviderBranches { get; set; }
        public virtual ICollection<ProviderImage> ProviderImages { get; set; }
        public virtual ICollection<ProviderPropertise> ProviderPropertises { get; set; }
        public virtual ICollection<ServiceOtherPrice> ServiceOtherPrices { get; set; }
    }
}
