//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOtherPrice
    {
        public long ServiceOtherPriceId { get; set; }
        public Nullable<long> ServiceOtherId { get; set; }
        public Nullable<long> ProviderId { get; set; }
        public Nullable<long> ContractId { get; set; }
        public Nullable<int> PaymenId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> FromDay { get; set; }
        public Nullable<System.DateTime> ToDay { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> PriceAdult { get; set; }
        public Nullable<decimal> PriceChild { get; set; }
        public Nullable<decimal> PriceInfant { get; set; }
        public Nullable<decimal> PriceBaby { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Payman Payman { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ServiceOther ServiceOther { get; set; }
    }
}
