//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOther
    {
        public ServiceOther()
        {
            this.ServiceOtherPrices = new HashSet<ServiceOtherPrice>();
        }
    
        public long ServiceOtherId { get; set; }
        public string Name { get; set; }
        public Nullable<int> NationalId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> WardId { get; set; }
        public string Address { get; set; }
        public string AddressShow { get; set; }
        public Nullable<long> LocationId { get; set; }
        public string Description { get; set; }
        public string Contents { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<ServiceOtherPrice> ServiceOtherPrices { get; set; }
    }
}
