//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long UserId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Image { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDay { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public bool Sex { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public bool Remember { get; set; }
        public Nullable<System.DateTime> LoginDay { get; set; }
        public Nullable<System.DateTime> RePassDay { get; set; }
        public Nullable<double> Point { get; set; }
        public Nullable<int> CareerId { get; set; }
        public string Diploma { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual Career Career { get; set; }
    }
}
