//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vocative
    {
        public Vocative()
        {
            this.Guides = new HashSet<Guide>();
            this.PartnerStaffs = new HashSet<PartnerStaff>();
        }
    
        public int VocativeId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ICollection<Guide> Guides { get; set; }
        public virtual ICollection<PartnerStaff> PartnerStaffs { get; set; }
    }
}
